version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 9200

  web:
    image: opencloudeu/opencloud:2
    user: "1000:1000"
    environment:
      TZ: "Europe/Berlin"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      PROXY_TLS: "false"
      PROXY_OIDC_ISSUER: "http://${DEVICE_DOMAIN_NAME}"
      OC_URL: "http://${DEVICE_DOMAIN_NAME}"
      OC_OIDC_ISSUER: "http://${DEVICE_DOMAIN_NAME}"
      INITIAL_ADMIN_PASSWORD: "umbrel"
      OC_CONFIG_DIR: "/etc/opencloud"
      OC_DATA_DIR: "/var/lib/opencloud"

      OC_JWT_SECRET: "y6vVb3w9qJkqV2mB0t1m6QbA1rN8fG4sD0pX2cH7uK9zT3eP5rL8uW2yQ6mC9aH4"
      OC_TRANSFER_SECRET: "p9Qk2Nf4wT7xVc3Jm8Rz1Ld6bG0hYs5Ue2Aq7Kp3Mn6Wv9Xc1Tr4Jg8Lz2Qh5Nw7"

      OC_SYSTEM_USER_ID: "b2f5ff47-8a8a-4a0d-9b1a-2c3d4e5f6071"
      OC_SYSTEM_USER_IDP: "internal"
      OC_SYSTEM_USER_API_KEY: "s0mE-Sup3r-Long-Mach1ne-Key_KeepItSecret"
      OC_MACHINE_AUTH_API_KEY: "z3Nq6Pp1Xs8Rw4Cv7Lm2Jt9Qe5Hb0Ka4Ud7Yi2Po9Rt6Wq1Lm3As8Df5Gh9Jk2Lq"

      STORAGE_USERS_MOUNT_ID: "7639e57c-4433-4a12-8201-722fd0009154"
      GATEWAY_STORAGE_USERS_MOUNT_ID: "7639e57c-4433-4a12-8201-722fd0009154"

      OC_LDAP_BIND_DN: "uid=reva,ou=sysusers,o=libregraph-idm"
      OC_LDAP_BIND_PASSWORD: "reva-bind-password"
      OC_LDAP_USER_BASE_DN: "ou=users,o=libregraph-idm"
      OC_LDAP_GROUP_BASE_DN: "ou=groups,o=libregraph-idm"
      IDP_LDAP_BIND_DN: "uid=idp,ou=sysusers,o=libregraph-idm"
      IDP_LDAP_BIND_PASSWORD: "idp-bind-password"
      AUTH_BASIC_LDAP_BIND_DN: "uid=reva,ou=sysusers,o=libregraph-idm"
      AUTH_BASIC_LDAP_BIND_PASSWORD: "reva-bind-password"
      GROUPS_LDAP_BIND_DN: "uid=reva,ou=sysusers,o=libregraph-idm"
      GROUPS_LDAP_BIND_PASSWORD: "reva-bind-password"

      IDM_SVC_PASSWORD: "idm-service-password"
      IDM_REVASVC_PASSWORD: "reva-service-password"
      IDM_IDPSVC_PASSWORD: "idp-service-password"

      GRAPH_APPLICATION_ID: "com.opencloud.app"
      GRAPH_APPLICATION_DISPLAYNAME: "OpenCloud"
      GRAPH_JWT_SECRET: "K2f7Pp9xQ3r8Sg1Lm6Vb4Nc0Hd2Jt5Ye7Rw1Zk8Mq4"

      OC_SERVICE_ACCOUNT_ID: "5c5b02a7-3c1b-4f0a-9c1e-2a7d8b9f1e22"
      OC_SERVICE_ACCOUNT_SECRET: "Tn7hV1qP4xR2sM8aL5cW0yB3kE6fZ9jD2uH4pQ7rS1vX8mN0"
      SEARCH_SERVICE_ACCOUNT_ID: "5c5b02a7-3c1b-4f0a-9c1e-2a7d8b9f1e22"
      SEARCH_SERVICE_ACCOUNT_SECRET: "Tn7hV1qP4xR2sM8aL5cW0yB3kE6fZ9jD2uH4pQ7rS1vX8mN0"
      USERLOG_SERVICE_ACCOUNT_ID: "5c5b02a7-3c1b-4f0a-9c1e-2a7d8b9f1e22"
      USERLOG_SERVICE_ACCOUNT_SECRET: "Tn7hV1qP4xR2sM8aL5cW0yB3kE6fZ9jD2uH4pQ7rS1vX8mN0"
      CLIENTLOG_SERVICE_ACCOUNT_ID: "5c5b02a7-3c1b-4f0a-9c1e-2a7d8b9f1e22"
      CLIENTLOG_SERVICE_ACCOUNT_SECRET: "Tn7hV1qP4xR2sM8aL5cW0yB3kE6fZ9jD2uH4pQ7rS1vX8mN0"
    volumes:
      - ${APP_DATA_DIR}/config:/etc/opencloud
      - ${APP_DATA_DIR}/data:/var/lib/opencloud
    restart: on-failure:5
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
