version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 9200

  web:
    image: opencloudeu/opencloud:2
    user: "1000:1000"
    environment:
      TZ: "Europe/Berlin"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      OC_INSECURE: "true"
      OC_URL: "https://${DEVICE_DOMAIN_NAME}"
      INITIAL_ADMIN_PASSWORD: "umbrel"
      OC_CONFIG_DIR: "/etc/opencloud"
      OC_DATA_DIR: "/var/lib/opencloud"

      OC_JWT_SECRET: "y6vVb3w9qJkqV2mB0t1m6QbA1rN8fG4sD0pX2cH7uK9zT3eP5rL8uW2yQ6mC9aH4"
      OC_TRANSFER_SECRET: "p9Qk2Nf4wT7xVc3Jm8Rz1Ld6bG0hYs5Ue2Aq7Kp3Mn6Wv9Xc1Tr4Jg8Lz2Qh5Nw7"

      OC_SYSTEM_USER_ID: "b2f5ff47-8a8a-4a0d-9b1a-2c3d4e5f6071"
      OC_SYSTEM_USER_IDP: "internal"
      OC_SYSTEM_USER_API_KEY: "s0mE-Sup3r-Long-Mach1ne-Key_KeepItSecret"
      OC_MACHINE_AUTH_API_KEY: "z3Nq6Pp1Xs8Rw4Cv7Lm2Jt9Qe5Hb0Ka4Ud7Yi2Po9Rt6Wq1Lm3As8Df5Gh9Jk2Lq"

      STORAGE_USERS_MOUNT_ID: "7639e57c-4433-4a12-8201-722fd0009154"
      GATEWAY_STORAGE_USERS_MOUNT_ID: "7639e57c-4433-4a12-8201-722fd0009154"
    volumes:
      - ${APP_DATA_DIR}/config:/etc/opencloud
      - ${APP_DATA_DIR}/data:/var/lib/opencloud
    restart: on-failure:5
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
