version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-noton_app_1
      APP_PORT: 6686

  app:
    image: ghcr.io/bartvantuijn/noton:latest
    restart: on-failure
    environment:
      APP_NAME: Noton
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://denny-noton_app_1:6686
      APP_LOCALE: en
      DB_CONNECTION: pgsql
      DB_HOST: denny-noton_postgres_1
      DB_PORT: 5432
      DB_DATABASE: noton_database
      DB_USERNAME: noton_user
      DB_PASSWORD: noton_password
      OLLAMA_BASE_URL: http://denny-noton_ollama_1:11434
      OLLAMA_MODEL: llama3.1:8b
      OLLAMA_TIMEOUT: 60
      OLLAMA_PULL_TIMEOUT: 600
    volumes:
      - ${APP_DATA_DIR}/data/noton/uploads:/srv/www/storage/app/public
    depends_on:
      - postgres
      - ollama

  postgres:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_DB: noton_database
      POSTGRES_USER: noton_user
      POSTGRES_PASSWORD: noton_password
    volumes:
      - ${APP_DATA_DIR}/data/noton/postgres:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/noton/ollama:/root/.ollama