version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-filesync_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: poliuscorp/filesync:latest
    restart: on-failure
    environment:
      SECRET_KEY: "password-123-filesync-umbrel-2026"
    depends_on:
      - peerjs

  peerjs:
    image: peerjs/peerjs-server:1.1.0-rc.2
    restart: on-failure
    command: peerjs --path /peerjs
    depends_on:
      - coturn

  coturn:
    image: coturn/coturn:alpine
    restart: on-failure
    command:
      - --fingerprint
      - --use-auth-secret
      - --no-multicast-peers
      - --realm=${DEVICE_DOMAIN_NAME}
      - --static-auth-secret=password-123-filesync-umbrel-2026
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
