version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-gameyfin_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/gameyfin/gameyfin:2.1.2@sha256:ddc99c9f7568f7640bb8d032f03786f0131756ea94964ebe8004176a493801ab
    restart: on-failure
    environment:
      APP_KEY: w/POFyFJaCMtAybm8U8Cq1mMetGnlhiviq9MWOZpKI4=
      PUID: 1000
      PGID: 1000
      #APP_URL: http://${DEVICE_DOMAIN_NAME}:8909
    volumes:
      - ${APP_DATA_DIR}/data/db:/opt/gameyfin/db:rw
      - ${APP_DATA_DIR}/data/gameyfin_data:/opt/gameyfin/data:rw
      - ${APP_DATA_DIR}/data/logs:/opt/gameyfin/logs:rw
      - ${APP_DATA_DIR}/data/games:/games:rw
