version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-excalidraw_app_1
      APP_PORT: 80 # Web client

  app:
    image: ghcr.io/ozencb/excalidraw-persist:0.18.0-persist.1@sha256:ea4604355b13a15b2071efb674aeb77411c30aa10c3721fe589a8eda319d0bef
    ports:
      - 4001:4000 # Server API
    restart: on-failure
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw

