version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-jotty_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/fccview/jotty:1.8.1@sha256:e7f886b916f1eeb1b848bc0b444e73c6ffd9f4e1c5a36f6f115ad6926dedc129
    restart: on-failure
    user: "0:0"
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/app/data:rw
      - ${APP_DATA_DIR}/data/config:/app/config:ro
      - ${APP_DATA_DIR}/data/cache:/app/.next/cache:rw
    environment:
      NODE_ENV: production
      SERVE_PUBLIC_IMAGES: yes
      SERVE_PUBLIC_FILES: yes
