version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-zipline_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: 'false'

  db:
    image: postgres:17.3@sha256:6e3358e46e34dae6c184f48fd06fe1b3dbf958ad5b83480031907e52b9ec2a7d
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: zipline
      POSTGRES_USER: ziplineuser
      POSTGRES_PASSWORD: ziplinepass
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'zipline', '-U', 'ziplineuser']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  web:
    image: ghcr.io/diced/zipline:4.6.4@sha256:3e3a57520e0bdf614b74676c4fe0f14c430215b6f659133ce108edc54a167a8c
    environment:
      DATABASE_URL: postql://ziplineuser:ziplinepass@db:5432/zipline?schema=public
      CORE_SECRET: 3b449077187f1150082fb348796e97be22b57fefdbd4a7b18f575b51f65519b7
      CORE_PORT: 3000
      CORE_HOSTNAME: 0.0.0.0
      DATASOURCE_TYPE: local
      DATASOURCE_LOCAL_DIRECTORY: /data/files
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/data/files:rw
      - ${APP_DATA_DIR}/data/public:/zipline/public:rw
      - ${APP_DATA_DIR}/data/themes:/zipline/themes:rw
    depends_on:
      - db
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://0.0.0.0:3000/api/healthcheck']
      interval: 15s
      timeout: 2s
      retries: 2
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: on-failure
