version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-oniondrop_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: dennysubke/oniondrop:0.2.0@sha256:e85eec9847ae9333f4fa109284af9059d5aff08631f74158bb8c6fabe314df0f
    restart: on-failure
    stop_grace_period: 30s
    environment:
      PUID: "1000"
      PGID: "1000"
      ONIONDROP_DATA_DIR: /data
      ONIONDROP_PORT: "8080"
      ONIONDROP_AUTH_MODE: setup
      ONIONDROP_DEFAULT_LANGUAGE: en
      ONIONSHARE_VERSION: "2.6.4"
    volumes:
      - ${APP_DATA_DIR}/data:/data
