version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-oniondrop_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: dennysubke/oniondrop:0.1.0@sha256:3514b55ccc6936771a24954bf1cff81b8c8a0f28d59ccd27385e3daac47a772c
    restart: on-failure
    stop_grace_period: 30s
    environment:
      PUID: "1000"
      PGID: "1000"
      ONIONDROP_DATA_DIR: /data
      ONIONDROP_PORT: "8080"
      ONIONSHARE_VERSION: "2.6.4"
    volumes:
      - ${APP_DATA_DIR}/data:/data
