version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-vert_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/vert-sh/vert:latest
    restart: on-failure
    environment:
      PUB_HOSTNAME: http://${DEVICE_DOMAIN_NAME}:3884
      PUB_VERTD_URL: http://${DEVICE_DOMAIN_NAME}:3884
      PUB_ENV: production
    volumes:
      - ${APP_DATA_DIR}/data:/data
