version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: denny-tubearchivist_web_1
      APP_PORT: 8000

  web:
    image: bbilly1/tubearchivist:latest
    container_name: denny-tubearchivist_web_1
    restart: on-failure
    depends_on:
      - archivist-es
      - archivist-redis
    environment:
      TZ: Europe/Berlin
      TA_USERNAME: admin
      TA_PASSWORD: umbrel
      ELASTIC_PASSWORD: umbrel
      ELASTIC_USER: elastic
      REDIS_HOST: archivist-redis
      REDIS_PORT: 6379
      ELASTIC_HOST: archivist-es
      ELASTIC_PORT: 9200
      TA_HOST: ${DEVICE_DOMAIN_NAME}
      TA_PORT: 8000
      TA_UWSGI_PORT: 8001
    volumes:
      - ${APP_DATA_DIR}/data:/data

  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: denny-tubearchivist_archivist-es_1
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=umbrel
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${APP_DATA_DIR}/es:/usr/share/elasticsearch/data

  archivist-redis:
    image: redis:7.4.0
    container_name: denny-tubearchivist_archivist-redis_1
    restart: on-failure
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - ${APP_DATA_DIR}/redis:/data
