version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: denny-tubearchivist_web_1
      APP_PORT: 8000

  web:
    image: bbilly1/tubearchivist:latest
    restart: on-failure
    depends_on:
      - archivist-es
      - archivist-redis
    environment:
      TZ: Europe/Berlin
      TA_USERNAME: admin
      TA_PASSWORD: umbrel
      TA_HOST: umbrel-2.local
      TA_PORT: 6686
      ES_URL: http://elastic:umbrel@archivist-es:9200
      REDIS_HOST: archivist-redis
      REDIS_PORT: 6379
    volumes:
      - ${APP_DATA_DIR}/data:/data

  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    restart: on-failure
    user: "0:0"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=umbrel
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${APP_DATA_DIR}/es:/usr/share/elasticsearch/data

  archivist-redis:
    image: redis:7.4.0
    restart: on-failure
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - ${APP_DATA_DIR}/redis:/data
