version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-btctracker_web_1
      APP_PORT: 3000

  web:
    image: thewilqq/btc-tracker:v0.6.2@sha256:18f27099139d5df0e5c153b8a2d7660c38ab75491df757afee6fa382635f8c63
    restart: on-failure
    user: 1000:1000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3947
    volumes:
      - ${APP_DATA_DIR}/data:/app/data





