version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-btctracker_web_1
      APP_PORT: 3000

  web:
    image: thewilqq/btc-tracker:v2025.10.28@sha256:28970995a541092655db03c43b7809bd3a41afdb27809565670f9246983ed250
    restart: on-failure
    user: 1000:1000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3947
    volumes:
      - ${APP_DATA_DIR}/data:/app/data




