version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-mykonos-island-voxels_web_1
      APP_PORT: 8080

  web:
    image: dennysubke/mykonos-island-voxels:ca5faee@sha256:ab7416a1a37ad3f92865b93533c2b7aa3ec46f08598dfe55f6c29b1af73e12b3
    user: "1000:1000"
    restart: on-failure
