version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-pokerogue_web_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"

  web:
    image: dennysubke/pokerogue:1.12.0.8@sha256:e11a5a8039ffea015ee133b60bdbc74c4d6ecf9c1ff20746c00c62bff2a75df2
    restart: on-failure