version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-crumbs_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/bretzel-app/crumbs:0.30.1@sha256:0559ace1bbf9bc60091b5f698db832b4282806842809cb2a51f119e65379e569
    volumes:
      - ${APP_DATA_DIR}/data:/data
