version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-btcpay-lbtc_web_1
      APP_PORT: 3003

  postgres:
    image: postgres:16.4-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: btcpay
      POSTGRES_DB: btcpay
      POSTGRES_PASSWORD: "S3cur3_P0stgr3s_2025!"
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data

  nbxplorer:
    image: btcpayserver/nbxplorer:2.6.0
    restart: on-failure
    environment:
      NBXPLORER_NETWORK: "mainnet"
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_DATADIR: "/data"
    volumes:
      - ${APP_DATA_DIR}/data/nbxplorer-btc:/data

  elementsd:
    image: elementsproject/elements:23.2.1
    restart: on-failure
    command:
      - "-chain=liquidv1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=elements"
      - "-rpcpassword=elements"
      - "-fallbackfee=0.0001"
    volumes:
      - ${APP_DATA_DIR}/data/elements:/root/.elements

  nbxplorer-elements:
    image: btcpayserver/nbxplorer:2.6.0
    restart: on-failure
    depends_on:
      - elementsd
    environment:
      NBXPLORER_NETWORK: "liquidv1"
      NBXPLORER_CHAINS: "lbtc"
      NBXPLORER_DATADIR: "/data"
      NBXPLORER_RPCURL: "http://elementsd:18884/"
      NBXPLORER_RPCUSER: "elements"
      NBXPLORER_RPCPASSWORD: "elements"
    volumes:
      - ${APP_DATA_DIR}/data/nbxplorer-elements:/data

  web:
    image: btcpayserver/btcpayserver:1.14.5
    restart: on-failure
    depends_on:
      - postgres
      - nbxplorer
    environment:
      BTCPAY_POSTGRES: "User ID=btcpay;Password=S3cur3_P0stgr3s_2025!;Host=postgres;Port=5432;Database=btcpay"
      ASPNETCORE_URLS: "http://0.0.0.0:4939"
      # Toggle Liquid here (edit in this compose file)
      ENABLE_LIQUID: "true"
      # Internal NBX URLs (used by entrypoint mapping below)
      NBX_LBTC_URL: "http://nbxplorer-elements:32838/"
      NBX_BTC_URL: "http://nbxplorer:32838/"
      # Optional extra flags (stay empty unless you know what you're doing)
      BTCPAY_ADDITIONAL_ARGS: ""
    command: ["/bin/sh", "/app/scripts/entrypoint.sh"]
    volumes:
      - ${APP_DATA_DIR}/data/btcpay:/data
      - ${APP_DATA_DIR}/data/logs:/logs
      - ${APP_DATA_DIR}/data/plugins:/root/.btcpayserver/Plugins
      - ${APP_DATA_DIR}/data/app:/app/data
      - ${APP_DATA_DIR}/app/scripts:/app/scripts
