version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-titra_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: titraio/titra:v1.0.10
    restart: on-failure
    depends_on:
      - titra-mongodb
    environment:
      ROOT_URL: "http://${DEVICE_DOMAIN_NAME}:3000"
      MONGO_URL: "mongodb://titra-mongodb:27017/titra?directConnection=true"
      PORT: "3000"

  titra-mongodb:
    image: mongo:7.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/mongodb:/data/db