version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-vidbee_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    depends_on:
      api:
        condition: service_healthy
    image: ghcr.io/nexmoe/vidbee-web:sha-14dcdae@sha256:a13881f5b2cd982a5a2e238a4e675dafd7cd602496309b0ea04bf844e659db54
    restart: on-failure
    environment:
      VIDBEE_API_URL_INTERNAL: http://api:3100
      VIDBEE_ALLOWED_HOSTS: "${DEVICE_DOMAIN_NAME},denny-vidbee_web_1"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:3000/ > /dev/null || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api:
    image: ghcr.io/nexmoe/vidbee-api:sha-14dcdae@sha256:429a9217c3b9cc78c31bc220b176f84738c2fb3a8a392fecdc38fee2176b709e
    restart: on-failure
    environment:
      VIDBEE_API_HOST: 0.0.0.0
      VIDBEE_API_PORT: 3100
      VIDBEE_DOWNLOAD_DIR: /data/downloads
      VIDBEE_HISTORY_STORE_PATH: /data/vidbee/vidbee.db
      VIDBEE_PERSIST_QUEUE: 1
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/vidbee:/data/downloads
      - ${APP_DATA_DIR}/data:/data/vidbee
      - ${APP_DATA_DIR}/data:/app/.data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:3100/health > /dev/null || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
