version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:11.5@sha256:e618069947985ec889e57ac68cc9dc42d9456904ee890393a1ec8d8cd705fb1e
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://umbrel-2.local:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400

