version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-twakedrive_frontend_1
      APP_PORT: 80

  mongo:
    image: mongo:7.0.14
    volumes:
      - ${APP_DATA_DIR}/data/mongo:/data/db

  tdrive_node:
    image: twakedrive/tdrive-node:latest
    environment:
      DEV: production
      SEARCH_DRIVER: mongodb
      DB_DRIVER: mongodb
      PUBSUB_TYPE: local
      MONGO_URL: mongodb://mongo:27017
    volumes:
      - ${APP_DATA_DIR}/data/documents:/storage
    depends_on:
      - mongo

  frontend:
    image: twakedrive/tdrive-frontend:latest
    environment:
      DEV: production
      NODE_HOST: http://tdrive_node:4000
      SSL_CERTS: off
    volumes:
      - ${APP_DATA_DIR}/data/logs/nginx:/var/log/nginx
      - ${APP_DATA_DIR}/data/letsencrypt:/etc/letsencrypt
      - ${APP_DATA_DIR}/data/drive-preview:/tdrive-core/web/medias
      - ${APP_DATA_DIR}/data/uploads:/tdrive-core/web/upload
    depends_on:
      - tdrive_node
